from ast_nodes import ProgramNode, RuleNode, IfNode, ConditionNode, AssignNode


class CodeGenerator:
    """
    Translates a ProgramNode AST into a Python source-code string.

    Usage:
        gen  = CodeGenerator()
        code = gen.generate(program_node)
        print(code)
    """

    # Header comment placed at the top of every generated file
    FILE_HEADER = (
        "# ================================================\n"
        "# Auto-generated by RuleScript Compiler\n"
        "# DO NOT EDIT — edit the .rules source instead.\n"
        "# ================================================\n\n"
    )

    def __init__(self):
        self._lines: list = []      # accumulate generated lines here

    #  Public entry point 

    def generate(self, program: ProgramNode) -> str:
        """
        Walk every rule in the program and emit Python code.
        Returns the complete generated source as a string.
        """
        self._lines = [self.FILE_HEADER]

        for rule in program.rules:
            self._gen_rule(rule)
            self._lines.append('\n')   # blank line between functions

        # Append a __main__ demo block so the file is runnable
        self._lines.append(self._demo_block(program))

        return ''.join(self._lines)

    #  Rule → Python function 

    def _gen_rule(self, rule: RuleNode):
        """
        RULE <name>
          IF   <condition>
          THEN <then_assign>
          ELSE <else_assign>   ← optional

        Becomes:
          def <name>(<condition.left>):
              if <condition.left> <op> <right>:
                  <then_var> = <then_val>
              else:
                  <else_var> = <else_val>
              return <then_var>
        """
        cond      = rule.if_node.condition
        then_body = rule.if_node.then_body
        else_body = rule.if_node.else_body

        #  Function signature 
        # Use the condition's left variable as the parameter
        param = cond.left
        self._emit(f'def {rule.name}({param}):')

        #  Docstring 
        self._emit(f'    """Auto-generated rule: {rule.name}"""')

        #  if statement 
        right_val = self._format_value(cond.right)
        self._emit(f'    if {cond.left} {cond.op} {right_val}:')

        #  THEN body 
        self._emit(f'        {then_body.variable} = {self._format_value(then_body.value)}')

        #  ELSE body (optional) 
        if else_body is not None:
            self._emit('    else:')
            self._emit(f'        {else_body.variable} = {self._format_value(else_body.value)}')

        #  return the assigned variable 
        self._emit(f'    return {then_body.variable}')

    #  Helper: format a value token as Python literal 

    @staticmethod
    def _format_value(value: str) -> str:
        """
        DSL values are stored as strings.
        Convert them to proper Python representation:
          '18'    → '18'      (stays an integer literal)
          'True'  → 'True'    (stays a boolean)
          'False' → 'False'
          'score' → 'score'   (stays an identifier)
        """
        # Boolean literals — already correct Python spelling
        if value in ('True', 'False'):
            return value

        # Numeric literal — keep as-is
        try:
            int(value)
            return value
        except ValueError:
            pass

        # Variable name — keep as-is
        return value

    #  Demo __main__ block 

    @staticmethod
    def _demo_block(program: ProgramNode) -> str:
        """
        Generate a small __main__ section that calls each rule
        with a sample value so the developer can run the file
        immediately and see output.
        """
        lines = [
            '\n',
            '# ── Quick demo (run this file directly) ────────\n',
            'if __name__ == "__main__":\n',
            '    print("=== RuleScript Generated Code — Demo ===")\n',
        ]
        for rule in program.rules:
            param = rule.if_node.condition.left
            # Use sample value 18 for numeric comparisons; True for boolean
            sample = '18'
            lines.append(
                f'    result = {rule.name}({sample})\n'
                f'    print(f"  {rule.name}({param}={sample}) => {{result}}")\n'
            )
        return ''.join(lines)

    #  Emit helper 

    def _emit(self, line: str):
        """Append a line (with newline) to the output buffer."""
        self._lines.append(line + '\n')
